bitmovin/bitmovin-javascript

README.md, bitmovin/encoding/statistics.js, tests/encoding/statistics.test.js
Added statistics.js and implemented overall statistics call
Added statistics.test.js
=> Overall statistics for encodings

bitmovin/bitmovin.js, bitmovin/encoding/infrastructure.js, examples/encoding/package.json, package.json, tests/encoding/infrastructure.test.js, tests_it/encoding/infrastructure.test.js
=> Added limit, offset GET parameters to list call.

examples/encoding/19_Create_per_title_encoding_mp4.js
=> added pertitle mp4 example

bitmovin/encoding/outputs.ts, tests/encoding/outputs.test.ts
Issue: https://github.com/bitmovin/dashboard/issues/381
Description: Added `bitmovinTempS3` output type
Tests: Added `bitmovinTempS3` type tests
=> Added temp s3 output

bitmovin/encoding/filters.ts, tests/encoding/filters.test.ts
Issue: https://github.com/bitmovin/dashboard/issues/381
Description: Added missing filter type calls
=> Added missing filter type calls

bitmovin/encoding/filters.ts, tests/encoding/filters.test.ts
Issue: https://github.com/bitmovin/dashboard/issues/381
Description: Added `audioVolume` filter type to filters
Tests: Added tests for the `audioVolume` filter type
=> Added audio volume filter type

bitmovin/analytics/index.ts, bitmovin/analytics/queries.ts, tests/analytics/queries.test.ts, tests/bitmovin.test.ts
Just another endpoint for our analytics ad queries
=> Added bitmovin.analytics.ads.queries

bitmovin/encoding/encodings/index.ts, tests/encoding/encodings.test.ts
Issues: https://github.com/bitmovin/dashboard/issues/1007
Work: added a get call for receiving the start object of an encoding, added test for the call
=> added call for getting start object

bitmovin/notifications/emails.ts, bitmovin/notifications/index.ts, bitmovin/notifications/types.ts, bitmovin/utils/types.ts, tests/notifications/emails/emails.test.ts, tests/notifications/index.test.ts
Issue: https://github.com/bitmovin/dashboard/issues/849
* Adds mute/unmute methods for all notifications.
* Adds method for usage reports notifications.
=> Notifications: Added usage reports & methods for mute/unmute

bitmovin/encoding/inputs.ts, bitmovin/encoding/outputs.ts, tests/encoding/inputs.test.ts, tests/encoding/outputs.test.ts
Issues: https://github.com/bitmovin/dashboard/issues/1273
Work: added calls and tests for rolebased s3 inputs and outputs
=> add rolebaseS3 input/output calls and tests

bitmovin/encoding/encodings/muxings.ts, tests/encoding/muxings.test.ts
Issue: https://github.com/bitmovin/dashboard/issues/1185
Work done: Added `broadcast-ts` to the api calls
Tests: Added tests for the broadcast-ts muxings
=> Added broadcast-ts muxings

bitmovin/encoding/encodings/muxings.ts, tests/encoding/muxings.test.ts
Issue: https://github.com/bitmovin/dashboard/issues/1260
Description: Added `progressive-webm` muxing
=> Added progressive webm muxing

bitmovin/analytics/licenses.ts, bitmovin/player/licenses.ts, tests/analytics/licenses.test.ts, tests/player/licenses.test.ts
https://github.com/bitmovin/dashboard/issues/642
=> Add create methods to use POST endpoints to create analytics/player licenses

bitmovin/analytics/index.ts, bitmovin/analytics/releases/platforms.ts, tests/analytics/licenses.test.ts
Issue: https://github.com/bitmovin/dashboard/issues/384
Description: Added `releases/platforms` calls for the analytics
Tests: Added tests for the `releases/platforms` calls
=> Added platform releases calls

bitmovin/encoding/inputs.ts, tests/encoding/inputs.test.ts
Issue: https://github.com/bitmovin/dashboard/issues/2223
Description: Added srt and zixi input api calls
=> Added srt and zixi inputs

bitmovin/analytics/index.ts, bitmovin/analytics/insights/IndustryInsightQueries.ts, bitmovin/analytics/insights/IndustryInsightsQueryBuilder.ts, examples/analytics/01_industry_insights.js
Added an endpoint for the `analytics/insights/industry` route.
=> Added industry insights endpoint

bitmovin/encoding/encodings/machineLearning/objectDetection.ts, tests/encoding/objectDetection.test.ts
related to [#2450](https://github.com/bitmovin/dashboard/issues/2450)
added resultsByTimestamp() endpoint
=> added results by timestamp endpoint

bitmovin/encoding/encodings/machineLearning/objectDetection.ts
used utils.buildListCallFunction instead to be able to use list() function parameters.
=> added used utils.list function to create make result calls

bitmovin/analytics/filters.ts, bitmovin/analytics/index.ts, examples/analytics/04_filters.js, tests/analytics/filters.test.ts
https://bitmovin.atlassian.net/browse/AN-946
=> AN-946 added new filter api for customUserId

bitmovin/analytics/queryBuilder.ts, tests/analytics/queries.test.ts
https://bitmovin.atlassian.net/browse/AN-899
=> AN-899 added method to set includeContext

bitmovin/analytics/metricQueryBuilder.ts, bitmovin/analytics/queryBuilder.ts, tests/analytics/queries.test.ts
https://bitmovin.atlassian.net/browse/AN-1178
Added partial Result Properties to query builder
added tests for properties
=> AN-1178 added partial result properties to query builder

bitmovin/analytics/filters.ts, package.json, tests/analytics/filters.test.ts
https://bitmovin.atlassian.net/browse/AN-1251
added video search endpoint
=> AN-1251 added video search endpoint

bitmovin/analytics/licenses.ts, tests/analytics/licenses.test.ts
Issue: https://bitmovin.atlassian.net/browse/AN-1342
=> AN-1342 Add license reodering
